//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.RentalOrder = new HashSet<RentalOrder>();
            this.Deposit = new HashSet<Deposit>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public bool Sex { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<RentalOrder> RentalOrder { get; set; }
        public virtual ICollection<Deposit> Deposit { get; set; }
    }
}
